### ISSUE TITLE
Add Function To Use In-Game Move Furniture Feature To Set Config Coordinates

### ISSUE THREAD

**Issue by d-rafferty** [d-rafferty/lethal-tube-removal#12]
Taking advantage of the in-game furniture moving tool could be an easy way to set custom coordinates for items that allow it. And possibly enabling it for items that don't to make this process significantly less painful.

**Comment by ItsGreyToday** [comment]
You can try looking at mrov's UnlockableDefaults mod on how to do this. If you were to do it this way, a bool var like for locking coordinates for that specific furniture would be a complementary feature.

**Comment by d-rafferty** [comment]
> You can try looking at mrov's UnlockableDefaults mod on how to do this

Great spot, I'll check that out. Thanks!
