### ISSUE TITLE
Incompatibility with "ShipWindows"

### ISSUE THREAD

**Issue by Fl4sHNoX** [d-rafferty/lethal-tube-removal#14]
Just wanted to bring a bit of awareness to this issue as I do not know on which side a possible "patch" could be made for it:

cf. https://github.com/jverif/lc-shipwindow/issues/15

---
TL;DR: My bad! It seems that the latest update of "LethalPipeRemoval" reset the config file entirely so that's why it wasn't working, my apologies!

**Comment by d-rafferty** [comment]
No worries! I think where I restructured the config file for the coordinates system it probably broke the formatting and reset all of it back to default.
