### ISSUE TITLE
doors are unable to close manually when main speaker is disabled

### ISSUE THREAD

**Issue by Noranecore** [d-rafferty/lethal-tube-removal#2]
exactly as the title says

**Comment by d-rafferty** [comment]
I hope that finding this bug did not lead to the demise of your crew. I'll disable the option while I find a fix. Thanks!

**Comment by d-rafferty** [comment]
I couldn't track down exactly why the ship door controls were tied to the speaker? But I did implement a workaround and fixed it. Thanks for the helpful report and finding the root cause of the bug!
