### ISSUE TITLE
[Request] Flatten floor and walls

### ISSUE THREAD

**Issue by MathiusXII** [d-rafferty/lethal-tube-removal#22]
I'd like to request to remove the part where the floor angles up where it joins to the walls, as well as all the columns on the walls in the first half of the ship when you walk in. (So the walls and floor are more flat)

If the wall columns are removed, it'd be necessary to be able to move the door control and camera so they're not floating.

**Comment by d-rafferty** [comment]
Unfortunately pretty much the entirety of the ships walls and floor structure is baked into one model, so it is not possible to alter them piece by piece.  There is only one object and it is called "ShipInside" and if you deactivate it, you can see the entirety of the ships walls and floors disappear. I've attached some screenshots to demonstrate. Sorry trust me I wish I could change them too!

### **Ship inside from inspector view**
![Lethal Company Screenshot 2024 04 21 - 12 26 28 00](https://github.com/d-rafferty/lethal-tube-removal/assets/90558421/090ba201-c00e-4706-9ca9-1e62fb78f0e7)

### **Active**
![Lethal Company Screenshot 2024 04 21 - 12 26 38 01](https://github.com/d-rafferty/lethal-tube-removal/assets/90558421/2c982ec9-b1e0-4981-abc7-68ddfb1d21c5)

### **Deactivated**
![Lethal Company Screenshot 2024 04 21 - 12 27 27 25](https://github.com/d-rafferty/lethal-tube-removal/assets/90558421/0d5775f0-2aa7-4df9-a5e4-a9e1144571a3)
