### ISSUE TITLE
[Feature Request] Add option to hide the Storage Cabinet

### ISSUE THREAD

**Issue by Lunxara** [d-rafferty/lethal-tube-removal#23]
So I recently started using ItemDeclutter by Mrov cus it's a lot more intuitive, and I noticed you don't have an option included to remove the Storage Cabinet, I would greatly appreciate if you could add that please. Thank you <3

**Comment by d-rafferty** [comment]
Seems like such an obvious option to have but somehow was just overlooked... lol yes I'll get a patch out for it later today!

**Comment by Lunxara** [comment]
> Seems like such an obvious option to have but somehow was just overlooked... lol yes I'll get a patch out for it later today!

Yay thank you lol yeah I was pretty surprised it wasn't there myself ^^

**Comment by d-rafferty** [comment]
Should be live in a few minutes with v1.6.3 and was added with #24 

Thanks for the suggestion!
