### ISSUE TITLE
[Request] Remove hard dependency on LethalConfig

### ISSUE THREAD

**Issue by MathiusXII** [d-rafferty/lethal-tube-removal#25]
It isn't actually needed to work, right?
I don't really want or need LethalConfig. Can this be a recommendation instead of a requirement?

**Comment by d-rafferty** [comment]
The way the config script is currently written it is actually necessary to function. I could rewrite it to not need LethalConfig.. but when I wrote this mod I decided to use it to make it more friendly to set up for the more casual audience; who probably wouldn't want to spend the time typing out true/false 50 times in a text file with how many options there are. I hope this doesn't come across as rude but I just don't really have the time to completely rewrite the config script so it can function without LethalConfig at the current time. I may circle back to this somewhere down the line but in all honestly probably not so I will mark this as unplanned for now. Sorry!

**Comment by MathiusXII** [comment]
No not at all. I didn't realize lethalconfig was actually a hard requirement for a reason.
