### ISSUE TITLE
Conflict with Levelloader's LethalModDataLib hard dependency

### ISSUE THREAD

**Issue by 1410677474** [d-rafferty/lethal-tube-removal#26]
levelloader is a very important module
leveloaderv1.2.2
bug code：
[06:30:06.9178189] [Error  :MaxWasUnavailable.LethalModDataLib] Failed to register ModData attributes in LethalTubeRemoval.TubeRemoval from Hamster.LethalTubeRemoval plugin: Could not resolve type with token 0100001f from typeref (expected class 'System.Diagnostics.DebuggerBrowsableAttribute' in assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')

**Comment by d-rafferty** [comment]
Yes Max - the creator of ModData - stopped by here not too long ago to try and help fix the conflict with this mod.. apparently it's still not working and to be honest I'm not sure why. I'll take another look at it soon if it's still not working.

**Comment by d-rafferty** [comment]
@MaxWasUnavailable if you've got any idea what's causing this I can dig, but to be honest I'm clueless unless I've somehow got something targeted incorrectly?

**Comment by MaxWasUnavailable** [comment]
I'm honestly not quite sure. Yours is the only one that this is happening with, in a list of 200-ish(?) mods that someone tried.

That being said, I did try-catch this section of my code, so there shouldn't be any actual issues for players beyond said caught exception showing up in logs.

How are you building your mod? Might be worth updating your dotnet installation just in case there's something weird there?

**Comment by d-rafferty** [comment]
I AM TOO EMBARASSED TO STATE WHAT WAS CAUSING THE ISSUE BUT IT HAS BEEN RESOLVED

<sub>I was building in debug instead of release like an absolute clown</sub>
