### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by MathiusXII** [d-rafferty/lethal-tube-removal#3]
The wire that comes off the teleporter button please.

Also would it be possible to config an object's coords if I just want to move something, not delete it?

**Comment by d-rafferty** [comment]
I have added the option for the wire to be removed with v1.4.1 that I have just pushed out. As for the coordinate configs, I do believe this would be possible, however the coordinates for items in the ship tend to be a bit... odd. This could end up being fairly time-consuming doing it for every item. I will open a new issue and mention you there. If there are just like, one or a few specific items you'd like to be able to move, comment them there and that would be a good jumping off point for me to attempt to implement that feature. Thanks for the requests!
