### ISSUE TITLE
[Suggestion] Remove cable/rods under the ship

### ISSUE THREAD

**Issue by Fl4sHNoX** [d-rafferty/lethal-tube-removal#4]
I would appreciate the ability to remove whatever this is supposed to be:

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/04c1a128-a7c2-4413-9334-81aec410f262)
![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/0b14e763-fe82-46e9-bee9-90b273c38de6)

Thanks for your work and efforts & thank you very much in advance for your consideration!

**Comment by d-rafferty** [comment]
So I went and checked this out and unfortunately that weird cable thing under the ship is part of the Left Machinery Box model from the outside of the ship. Whole models are unable to be altered, so the only option to get rid of this is to remove the left machinery box. There is an option in the config already to remove all outside machinery, which removed the boxes from the left and right of the ship. To give a little more control, with #7 I have added a separate option to only remove the left machinery box, which will in turn delete those cable things, however _either_ option you choose will delete them. Thanks for the suggestions!

**Comment by Fl4sHNoX** [comment]
Thanks for adding it! However there seems to be another thing that's not getting removed when simply setting "Left Machinery" to true:

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/dac588df-c82d-45fb-b8ca-b4b10c42159a)

**Comment by d-rafferty** [comment]
@Fl4sHNoX Oh oops I forgot a line to remove that! I'll get that fixed in a bit and push it out!

**Comment by d-rafferty** [comment]
Should be fixed in v1.4.3 whenever that hits the storefront (usually takes a few minutes) with #8
