### ISSUE TITLE
[Coords Request] Door Button & Monitor

### ISSUE THREAD

**Issue by MathiusXII** [d-rafferty/lethal-tube-removal#41]
I forget if I already asked or not, but can the door monitor and button panel be moved?

**Comment by d-rafferty** [comment]
Okay now that I've finished up the changes for 1.7.0 I'll look into this. I'm not sure because the door stuff can be super finicky and not function properly if changed, but I'll definitely look into it in the next day or so!

**Comment by d-rafferty** [comment]
Alright! Finally got around to getting this done. Worked without any issues in solo play. However I was not able to test this online. Should not make any difference normally, but you never know with that damn door. Let me know if you run into any issues! The Company appreciates your service.

Live in v1.7.3 - Added with #49
