### ISSUE TITLE
Removing the door monitor after using OpenBodyCams causes problems with the camera

### ISSUE THREAD

**Issue by 1410677474** [d-rafferty/lethal-tube-removal#42]
![9DEXMP{Z3WR0 )9Y`ZED( 7](https://github.com/d-rafferty/lethal-tube-removal/assets/163803538/29a38620-4d2a-4898-ba2e-4b7db5ba41a1)

**Comment by d-rafferty** [comment]
This should be resolved in the new update v1.7.0 from #44 

In my limited testing BodyCams seemed to be working fine now that the removal method is changed. Let me know if you run into anymore issues with this.
