### ISSUE TITLE
Lag after the 1.7.0 update

### ISSUE THREAD

**Issue by Lunxara** [d-rafferty/lethal-tube-removal#45]
So all I can guess is that my issue I've been having regarding lag boils down to this mod, for some reason I noticed the game was running a lot less smoother than usual while on any planet today after the new update and I'm not really sure why. I hope you can maybe look into this ^^

**Comment by d-rafferty** [comment]
Yeah I'll take a look and try to see if I can figure out what's going on. I switched up the way the items are deleted for compatibility purposes and that's likely causing some issues I'll have to sort out. 

Is that lag only while in/around the ship, or in general while playing?

Also, there is an option at the very bottom of the config that allows you to go back to the old system of deletion, as long as it's not conflicting with any other mods you have, this should be perfectly fine to use while I iron out any issues that may be caused by the new method. Thanks! @Lunxara

**Comment by Lunxara** [comment]
> Yeah I'll take a look and try to see if I can figure out what's going on. I switched up the way the items are deleted for compatibility purposes and that's likely causing some issues I'll have to sort out.
> 
> Is that lag only while in/around the ship, or in general while playing?
> 
> Also, there is an option at the very bottom of the config that allows you to go back to the old system of deletion, as long as it's not conflicting with any other mods you have, this should be perfectly fine to use while I iron out any issues that may be caused by the new method. Thanks! @Lunxara

In general while playing, upon further investigating it seems like it didn't like me disabling the door monitor as a test after the update cus after reenabling it it seems to be performing like it did before, I wonder if it's something to do with unrendering the monitor but not the camera outside or something

**Comment by d-rafferty** [comment]
That's definitely it then, I've had issues with that door monitor several times. I previously had the outside cam removed as a fix, but reverted that because with the new system it seemed to be working okay.. clearly it is not.  I'll look into it and see if I can get a fix out tonight.

**Comment by d-rafferty** [comment]
Okay so I pushed out update v1.7.1 - #46 

This contains the option to turn off either of the cameras. I couldn't find anything definitive when running some tests, and I didn't find any issues in the logs either. I'm hoping that having the option to turn off the cameras could solve your issues. Play around with those and see if either of them help your performance? 

Please let me know how it goes. Thanks for your help! @Lunxara

**Comment by Lunxara** [comment]
> Okay so I pushed out update v1.7.1 - #46
> 
> This contains the option to turn off either of the cameras. I couldn't find anything definitive when running some tests, and I didn't find any issues in the logs either. I'm hoping that having the option to turn off the cameras could solve your issues. Play around with those and see if either of them help your performance?
> 
> Please let me know how it goes. Thanks for your help! @Lunxara

Will do!!! Yeah nothing logged for me either strangely enough, just had a noticeable performance loss while landed on any moon I went to haha

**Comment by Lunxara** [comment]
Yeah being able to unrender that camera outside seemed to help a lot, I wonder if the game was throwing a fit cus it had no screen to render to cus I unrendered the door cam and I have the external camera also disabled in General Improvements lol

**Comment by d-rafferty** [comment]
Yes that makes sense. This was very similar to the issue I had before but it would at least throw errors when in line of sight of the screens. I didn't see any errors so I assumed it was fine.. lol. In a future update I'll likely leave the option to keep them on, but I think I'll bundle those options into their own category so I can note to player's the performance issues like the ones you experienced while the cams are still on. Thank you again for your help!
