### ISSUE TITLE
[Suggestion] Remove bunkbed's hanging towel/cloth + towel hanger/rack

### ISSUE THREAD

**Issue by Fl4sHNoX** [d-rafferty/lethal-tube-removal#5]
Could it be possible to add the ability to remove the towel/cloth hanging on the bunkbed?

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/b27b1b39-0784-4b02-8671-469da9b1a866)

**Comment by d-rafferty** [comment]
As was the issue with the cables in issue #4 that towel is baked in as part of the bunkbed model. Which unfortunately means it is unable to be removed. I appreciate the suggestions! If you have any more feel free to submit them and sorry this couldn't be done!
