### ISSUE TITLE
New Update Breaks OuterDoorButtons Mod

### ISSUE THREAD

**Issue by Sourceshard** [d-rafferty/lethal-tube-removal#50]
The new update that controls door panel position breaks Outer Door Buttons Mod.

Outer door buttons clones the open button and places it on the outside of the ship.
By default with everything disabled after update the large outside button is moved on top of the panel. Making it almost impossible to use and breaking the Outer Door Button mod.

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/37197624/578c50b3-a980-48f7-ac04-dd995cc1bab9)

https://thunderstore.io/c/lethal-company/p/CTNOriginals/OuterDoorButtons/

**Comment by d-rafferty** [comment]
I know what caused this. I'll get a fix out shortly.

**Comment by d-rafferty** [comment]
Fixed with #52 

Live in v1.7.4
