### ISSUE TITLE
Mods Breaking When Lethal Tube Removal Configs Are Used

### ISSUE THREAD

**Issue by Sourceshard** [d-rafferty/lethal-tube-removal#51]
Due to the fact that Lethal Tube Removal Deletes/Destroys game objects, mods that reference or use these objects fail and crash the game. 

If possible please rewrite Lethal Tube Removal to either destroy elements earlier so developers can detect that they're being destroyed when they try to use them (Unity deferred destruction makes this very screwy), or preferably elements should be deactivated instead of destroying the objects. (much easier, cleaner, and less likely to break random mods that try to use things that normally exist on the ship)

Also, I highly recommend joining the Lethal Company Modding Discord and opening up a mod thread for Lethal Tube Removal. There are many modding resources available and people willing to help with these changes. 

https://discord.gg/fNyNXUCr

**Comment by d-rafferty** [comment]
We are already working on this #43 

As of v1.7.0 objects are set inactive by default instead of removal. But I am currently working on just turning off the renderer and colliders so they are even still active.
