### ISSUE TITLE
Main Display duplicates on monitors that have cameras disabled

### ISSUE THREAD

**Issue by Lunxara** [d-rafferty/lethal-tube-removal#55]
So this is a weird thing, but when disabling the Internal and External cameras with LethalPipeRemoval the Main display gets copied onto the External Cam Monitor and Internal Cam Monitor, would it be possible to use the Screen Off Material instead for them?
![20240707210847_1](https://github.com/d-rafferty/lethal-tube-removal/assets/54687368/0adb062c-35df-46d0-8c29-3fba99c96e41)

**Comment by d-rafferty** [comment]
I will take a look at this. I had this issue before when testing but sometimes it would happen and sometimes it wouldn't and could never narrow it down. I'll look at trying to do that for the screens as a band-aid fix because I do not know why this occurs.

**Comment by d-rafferty** [comment]
I can't seem to replicate this.. although I certainly know this has happened to me before as well. You are using OpenMonitors on v55 correct? I would just like to find the source of the issue instead of slapping a black square over it because if someone were to try to use this screen for something else it would likely cause some issues.

**Comment by d-rafferty** [comment]
In my testing, I found that this occurs somewhat randomly it seems when the cameras are off.  I don't have access to the streams feeding data to the monitor within this mod, and would be well out of scope. I could do a bandaid fix of black screens, but that would likely cause conflicts with other mods I would have to deal with as well.

This sounds like a customer service desk answer, but in my testing just returning to the menu and reloading the lobby fixed it in every instance I tested. So maybe just try doing that and pray to the The Company that it will go away. As of now it unfortunately seems like the easiest option. 

If this continues to be an issue and reloading will not fix it, please let me know. Thanks!

**Comment by Lunxara** [comment]
> In my testing, I found that this occurs somewhat randomly it seems when the cameras are off. I don't have access to the streams feeding data to the monitor within this mod, and would be well out of scope. I could do a bandaid fix of black screens, but that would likely cause conflicts with other mods I would have to deal with as well.
> 
> This sounds like a customer service desk answer, but in my testing just returning to the menu and reloading the lobby fixed it in every instance I tested. So maybe just try doing that and pray to the The Company that it will go away. As of now it unfortunately seems like the easiest option.
> 
> If this continues to be an issue and reloading will not fix it, please let me know. Thanks!

Lol well if it helps any the issue got fixed when I was able to readd GeneralImprovements to my pack after it got updated c; I also turned off the post processing for those monitors in GI's settings which provided an extra boost to performance over the boost already given from disabling the cams lol
