### ISSUE TITLE
[Suggestion] Make the default removal mode be Inactive instead of Renderer

### ISSUE THREAD

**Issue by Lunxara** [d-rafferty/lethal-tube-removal#56]
I highly recommend switching the default removal mode from Renderer to Inactive, this provides a performance boost in my testing and also fixes a HDRP Render Graph error that I've noticed sometimes occurred in my logs. I switched the removal mode to Inactive after Zaggy1024 the dev of OpenBodyCams suggested to do so and it helped out a lot ^^ if you'd like to see the errors I was getting in question I've attached a file for you.
[message.txt](https://github.com/user-attachments/files/16215823/message.txt)

**Comment by d-rafferty** [comment]
Very interesting. Okay yeah I think I'll do that. Thanks for the heads up.

**Comment by Lunxara** [comment]
> Very interesting. Okay yeah I think I'll do that. Thanks for the heads up.

You're Very Welcome ^^

**Comment by d-rafferty** [comment]
Inactive is now the default renderer, performance improvements are definitely noticeable. Thanks for bringing this to my attention. It is live in v1.7.6
#58
