### ISSUE TITLE
[Suggestion] Add bunkbed reposition config.

### ISSUE THREAD

**Issue by se3ya** [d-rafferty/lethal-tube-removal#57]
I would like to see bunkbed repositioning config. I have shipwindows mods which adds 4 new windows to the ship and one of them is behind the terminal, and the best idea was replacing it on the opposite wall. But there is on the opposite wall bunkbeds. And I have a mod Bunkbed Revive that makes bunkbeds usable.

**Comment by d-rafferty** [comment]
Yes this is no problem I will work on this and get an update out soon!

**Comment by d-rafferty** [comment]
This has been added in v1.7.6 which is now live! Added in #58
