### ISSUE TITLE
[Suggestion] Add config options to set ship item coordinates

### ISSUE THREAD

**Issue by d-rafferty** [d-rafferty/lethal-tube-removal#6]

**Comment by d-rafferty** [comment]
@MathiusXII as per the other issue I commented on, just let me know if there are one, or a few, initial items you'd like to have custom coordinates for.

**Comment by Fl4sHNoX** [comment]
Personally I would appreciate having both teleporters' buttons neatly positioned somewhere, either on the desk or maybe make the appear on the console near the lever?

EDIT: maybe like this since we can't even make out the sign on the console anyways?
![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/a9031689-0107-4095-9746-a200a9c4a13a)

Another option would be to place them where the small batteries are currently but I don't know how well it would fit?

EDIT: maybe like that?
![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/17706e68-93d1-4523-b8e1-4f989b306b85)


Or maybe even on the Terminal but I think since you can move it it would probably be hard to bind the buttons to it...?


I would love to experiment and see for myself where it would fit best but I'm leaving it up to you! 
Feel free to share screenshots if you get to experiment with it!

**Comment by d-rafferty** [comment]
@Fl4sHNoX Okay no problem I'll see what I can do tonight!

**Comment by MathiusXII** [comment]
@d-rafferty Thanks. I was mainly wanting to move the suit rack, charging coil, and clipboard

**Comment by Fl4sHNoX** [comment]
I was actually about to ask to be able to move the suit rack as well since it triggers me in various ways:

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/f2333438-e085-4322-8d1c-073beaf4ab82)

The fact that it's kinda floating in the air is the main issue for me, and the other one would be solved just by being able to move it somewhere else because one of its feet is kinda floating above the FloorWindow from the "ShipWindow" mod.

But I +1 @MathiusXII 's suggestion of being able to move the charging coil, that's actually something I didn't think about but would be nice as well!

**Comment by d-rafferty** [comment]
I have added the option for custom coordinates of the charging station with v1.4.4 which is out now.
There are more details about how that works here -> #9 

The button reposition will be the next thing I add, and then I will begin work on the clothing rack. The clothing rack is more complicated because it is actually several different objects all sitting together, and moving them will be tough. I haven't tested for sure yet but this option will likely be incompatible with anything other than the default suit because they're all separate objects that need to be moved.

I attempted the clipboard coordinate option with this update, but since it is a physics object you can pick up it behaves very differently, although I do believe it can be done I just have to find the right method. @MathiusXII to be clear, did you just want to be able to have it spawn somewhere else? Because I did experiment a bit with having it spawn on the wall and trying to have the pages turn without picking it up, think of how you'd interact with a calendar. Let me know your preference!

**Comment by MathiusXII** [comment]
@d-rafferty Just where it spawns, though having it static is a neat idea. It's annoying to me when the teleporter buttons appear inside it's default spot. I do have a mod that can move it to be on the wall next to the coil charger, but I cannot remember which mod does it, and I'd honestly rather turn that off since it seems to teleport back on the wall when you reload the save. I could've sworn it was General Improvements, but I can't find that setting in the config...

**Comment by ItsGreyToday** [comment]
Can we also have custom coordinates for the terminal? My problem with the current coordinates from having Terminal Reposition = true is that it collides with the "extra monitors" from General Improvements' better monitors.

**Comment by MathiusXII** [comment]
@ItsGreyToday There is a mod called "Unlockable Defaults" that's supposed to let you set the default coords of furniture, but it only seems to work with the 4 default furnitures (cupboard, file cabinet, bunkbeds, and computer). Could use that for the time being.

**Comment by ItsGreyToday** [comment]
@MathiusXII thanks for the suggestion. I'll try it right away.

**Comment by Noranecore** [comment]
> @ItsGreyToday There is a mod called "Unlockable Defaults" that's supposed to let you set the default coords of furniture, but it only seems to work with the 4 default furnitures (cupboard, file cabinet, bunkbeds, and computer). Could use that for the time being.

This mod doesn't really work well (or at all from the last time I tested)

**Comment by d-rafferty** [comment]
@ItsGreyToday Yeah that should be no problem! Now that I have a boilerplate of how to adjust the coordinates for basic ship items it's just a matter of copy-paste and changing some variables around. I'd do it for everything immediately but I have to write 6 config entries for all of the coordinates for each item and doing that to every single item would be quite time consuming. I'll hopefully get that pushed out tomorrow with the buttons patch and I'll update this thread when I do!

**Comment by MathiusXII** [comment]
@ItsGreyToday Weird. It works for me on those 4 furnitures.
But looks like we'll have a replacement soon. Thanks @d-rafferty

**Comment by d-rafferty** [comment]
These fixes should be live with v1.5.0

There were some quirks with moving the buttons, as outlined in the link above, or here #11 
The inverse teleporter button glass when opened does clip into the monitor a bit, and it could be a bit hard to use in an emergency scenario, so I plan to add the option to move them to the right side of desk soon, it is just very annoying moving them because of the rotation issue I talked about in that post. But I will implement that sometime this weekend.

The custom terminal coordinate function should be active now, details in that link as well. 

The next thing I work on will likely be trying to add the movable suit rack, but I'm not making any promises because I anticipate that to be quite the task lol. I will also reexamine adding coordinates for the clipboard.

**Comment by d-rafferty** [comment]
Also, I will leave this thread open for suggestions/discussion! But if you run into any bugs or issues please create a separate issue post because this thread is getting quite long and hard to keep track of :)

**Comment by Fl4sHNoX** [comment]
I just tested the new placement for teleporter buttons (thanks a lot for making it! 🙏) and now I see the possible issues and wanted to suggest an alternative placement for them on the main console:

![image](https://github.com/d-rafferty/lethal-tube-removal/assets/3759901/21ad730a-0f0a-48fe-9570-b728d27bd585)


But I really like the enhancement idea you brought up here https://github.com/d-rafferty/lethal-tube-removal/issues/12, and if you mange to make it work my previous placement suggestion would obviously be obsolete!

**Comment by d-rafferty** [comment]
> ![image](https://private-user-images.githubusercontent.com/3759901/313512036-21ad730a-0f0a-48fe-9570-b728d27bd585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzAzNzAsIm5iZiI6MTcxMDczMDA3MCwicGF0aCI6Ii8zNzU5OTAxLzMxMzUxMjAzNi0yMWFkNzMwYS0wZjBhLTQ4ZmUtOTU3MC1iNzI4ZDI3YmQ1ODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDI0NzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFkOGY5MjZhYjY1YjA1OWVlYjM4OTU1ZDVlYTY4ZjNkODhjMTBjZjY4ZTg4YmY1ZGQ5Yzk5MDI5NGIwNzhkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6UaFFGyLfguuKngUUA_kKIamqFBcMdsol4PIA7rhlJw)
> 
Added with v1.5.1 
#15 @Fl4sHNoX

**Comment by d-rafferty** [comment]
@MathiusXII Sorry for the long wait. I've been very busy and haven't had time to work on this mod. I have added the ability to move the clipboard with custom coordinates in the latest update v1.6.2!

However currently it will reload the clipboard back to the custom position every time you reload the save. This is something I plan to fix in a future update.

**Comment by MathiusXII** [comment]
@d-rafferty Cool, thanks.
By the way, could you add coords to the air filter, oxygen tanks, and vent at the charging coil?

**Comment by d-rafferty** [comment]
> @d-rafferty Cool, thanks. By the way, could you add coords to the air filter, oxygen tanks, and vent at the charging coil?

Sorry for the long response time, been swamped with work lately and haven't had much time for this mod. Yes I will add these in the next patch in a day or two!

EDIT: 

Also to note, I will likely be placing all of these, and probably clipboard and coil as well, at the bottom of the config menu; as it is burying the more commonly used options, I would honestly advise trying to use the actual config file to edit these values if not already doing so. Is probably much more convenient

**Comment by d-rafferty** [comment]
Added coord options for the tank, filter and vent! However the current defaults are not correct and yeet them into space, so you're on your own for now, I hope I can eventually get around to correcting them. #34 

This will be live in v1.6.6

**Comment by MathiusXII** [comment]
@d-rafferty 
I forget if I already asked or not, but can the door monitor and button panel be moved?

**Comment by d-rafferty** [comment]
I will give them a shot. I'm actually currently working on the door monitor removal option right now and the game does not like it at all when you try to do anything with that monitor as it is constantly trying to feed it information from the cams. And the door is very finicky with any sort of change whatsoever, so I will give it a go but no guarantees. 

However please do me a favor and open a new issue for those two if you would, this thread is too long and I forget about things in here lol. @MathiusXII
